version: '3.8'

services:
  neo4j:
    image: neo4j:5.16.0
    container_name: neo4j2
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - $HOME/neo4j3/NGI-wiki:/data
      - $HOME/neo4j3/logs:/logs
      - $HOME/neo4j3/import:/var/lib/neo4j/import
      - $HOME/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled= true
      - NEO4J_apoc_import_file_enabled= true
      - NEO4J_apoc_import_file_use__neo4j__config= true
      - NEO4JLABS_PLUGINS= '["apoc"]'
      - NEO4J_dbms_security_procedures_unrestricted= apoc.*
    networks:
      - hay

networks:
  hay:
    driver: bridge